export const INVITATION_PALETTES = [
  {
    id: "clasico",
    name: "Clásico",
    description: "Verde salvia y crema",
    colors: {
      bg: "#f7f4e6",
      card: "#ffffff",
      ink: "#242424",
      muted: "#6b6b6b",
      primary: "#96a88f",
      secondary: "#3b3735",
      accent: "#cfcfcf",
      cta: "#96a88f",
      ctaText: "#ffffff",
    },
  },
  {
    id: "rosa",
    name: "Romántica",
    description: "Rosa suave",
    colors: {
      bg: "#fdf2f6",
      card: "#ffffff",
      ink: "#3b2f35",
      muted: "#8a6b76",
      primary: "#e8a0b8",
      secondary: "#b76e8f",
      accent: "#f6d7e2",
      cta: "#b76e8f",
      ctaText: "#ffffff",
    },
  },
  {
    id: "dorado",
    name: "Elegante",
    description: "Crema y dorado",
    colors: {
      bg: "#fbf6ec",
      card: "#ffffff",
      ink: "#3a3126",
      muted: "#8a7a63",
      primary: "#d4af6a",
      secondary: "#9c7a3c",
      accent: "#efe0c4",
      cta: "#9c7a3c",
      ctaText: "#ffffff",
    },
  },
  {
    id: "azul",
    name: "Sereno",
    description: "Azules suaves",
    colors: {
      bg: "#eef3fb",
      card: "#ffffff",
      ink: "#24313f",
      muted: "#5f7286",
      primary: "#7fa3c9",
      secondary: "#3f5f86",
      accent: "#d5e2f2",
      cta: "#3f5f86",
      ctaText: "#ffffff",
    },
  },
  {
    id: "moderno",
    name: "Moderno",
    description: "Negro y beige",
    colors: {
      bg: "#f4efe6",
      card: "#ffffff",
      ink: "#1c1a15",
      muted: "#746b5a",
      primary: "#17150f",
      secondary: "#a0906f",
      accent: "#e0d6c2",
      cta: "#17150f",
      ctaText: "#f4efe6",
    },
  },
  {
    id: "morado",
    name: "Sutil",
    description: "Lila y morado",
    colors: {
      bg: "#f3eefa",
      card: "#ffffff",
      ink: "#2f2940",
      muted: "#6d6388",
      primary: "#a58ac9",
      secondary: "#7a5ea8",
      accent: "#ddd0ef",
      cta: "#7a5ea8",
      ctaText: "#ffffff",
    },
  },
];

export function getPalette(id) {
  return INVITATION_PALETTES.find((p) => p.id === id) || INVITATION_PALETTES[0];
}
